FROM python:3.14-slim

WORKDIR /app

# Install dependencies
COPY agent/requirements.txt /app/agent/requirements.txt
RUN pip install --no-cache-dir -r agent/requirements.txt

# Copy application code
COPY agent/ /app/agent/
COPY config/ /app/config/

# Create runtime directories
RUN mkdir -p /app/agent/missions /app/agent/approvals /app/agent/logs \
    && echo '{"autoGenerated":true,"capabilities":{}}' > /app/agent/capabilities.json \
    && echo '[]' > /app/agent/services.json \
    && touch /app/agent/telemetry.jsonl

EXPOSE 8003

HEALTHCHECK --interval=10s --timeout=5s --start-period=15s --retries=3 \
    CMD python -c "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8003/api/v1/health')" || exit 1

CMD ["python", "-m", "uvicorn", "api.server:app", "--host", "0.0.0.0", "--port", "8003"]
WORKDIR /app/agent
