"""Auth integration tests — D-117.

Tests auth middleware with real config/auth.json in place.
Verifies operator/viewer/invalid/missing key behavior.
"""
import json
import os
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

# Setup test environment before importing app
_tmpdir = tempfile.mkdtemp(prefix="auth_test_")
_missions_dir = Path(_tmpdir) / "missions"
_missions_dir.mkdir()
_approvals_dir = Path(_tmpdir) / "approvals"
_approvals_dir.mkdir()
_telemetry_path = Path(_tmpdir) / "telemetry.jsonl"
_telemetry_path.write_text("")
_caps_path = Path(_tmpdir) / "capabilities.json"
_caps_path.write_text(json.dumps({"autoGenerated": True, "capabilities": {}}))
_services_path = Path(_tmpdir) / "services.json"
_services_path.write_text("{}")
_log_path = Path(_tmpdir) / "api.log"

# Auth config with test keys
_auth_config = {
    "keys": [
        {"key": "vz_test_op_key", "name": "test-operator", "role": "operator", "created": "2026-01-01"},
        {"key": "vz_test_vw_key", "name": "test-viewer", "role": "viewer", "created": "2026-01-01"},
    ]
}
_auth_dir = Path(_tmpdir) / "config"
_auth_dir.mkdir()
_auth_path = _auth_dir / "auth.json"
_auth_path.write_text(json.dumps(_auth_config))

import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import api.server as srv
srv.MISSIONS_DIR = _missions_dir
srv.APPROVALS_DIR = _approvals_dir
srv.TELEMETRY_PATH = _telemetry_path
srv.CAPABILITIES_PATH = _caps_path
srv.SERVICES_PATH = _services_path
srv.API_LOG_PATH = _log_path

from api.normalizer import MissionNormalizer
from api.capabilities import CapabilityChecker
srv.normalizer = MissionNormalizer(_missions_dir, _telemetry_path, _caps_path, _approvals_dir)
srv.capability_checker = CapabilityChecker(str(_caps_path))

from fastapi.testclient import TestClient

# Patch keys module to load from our test config
import auth.keys as keys_mod
_original_load = keys_mod._load_keys


def _patched_load():
    """Load keys from test auth config instead of default path."""
    keys_mod._keys = {
        entry["key"]: keys_mod.ApiKey(
            key=entry["key"],
            name=entry["name"],
            role=entry["role"],
            created=entry.get("created", ""),
        )
        for entry in _auth_config["keys"]
    }
    keys_mod._loaded = True


keys_mod._load_keys = _patched_load
keys_mod._loaded = False  # Force reload with patched function

client = TestClient(srv.app)

OP_HEADERS = {"Authorization": "Bearer vz_test_op_key"}
VW_HEADERS = {"Authorization": "Bearer vz_test_vw_key"}
BAD_HEADERS = {"Authorization": "Bearer vz_invalid_key"}


class TestAuthIntegration(unittest.TestCase):
    """Auth integration tests with real config/auth.json."""

    def test_01_get_endpoints_public(self):
        """GET endpoints work without auth."""
        r = client.get("/api/v1/health")
        self.assertEqual(r.status_code, 200)

        r = client.get("/api/v1/missions")
        self.assertEqual(r.status_code, 200)

    def test_02_operator_can_create_mission(self):
        """Operator key allows mission creation."""
        r = client.post(
            "/api/v1/missions",
            json={"goal": "auth test mission"},
            headers={**OP_HEADERS, "Origin": "http://localhost:3000"},
        )
        self.assertIn(r.status_code, (201, 200))

    def test_03_viewer_denied_mutation(self):
        """Viewer key gets 403 on mutation."""
        r = client.post(
            "/api/v1/missions",
            json={"goal": "viewer test"},
            headers={**VW_HEADERS, "Origin": "http://localhost:3000"},
        )
        self.assertEqual(r.status_code, 403)

    def test_04_invalid_key_denied(self):
        """Invalid key gets 401."""
        r = client.post(
            "/api/v1/missions",
            json={"goal": "invalid test"},
            headers={**BAD_HEADERS, "Origin": "http://localhost:3000"},
        )
        self.assertEqual(r.status_code, 401)

    def test_05_missing_auth_denied(self):
        """Missing auth header gets 401 when auth is enabled."""
        r = client.post(
            "/api/v1/missions",
            json={"goal": "no auth test"},
            headers={"Origin": "http://localhost:3000"},
        )
        self.assertEqual(r.status_code, 401)

    def test_06_get_still_works_without_auth(self):
        """GET endpoints don't require auth even when auth is enabled."""
        r = client.get("/api/v1/capabilities")
        self.assertEqual(r.status_code, 200)

        r = client.get("/api/v1/approvals")
        self.assertEqual(r.status_code, 200)


class TestAuthDisabled(unittest.TestCase):
    """Tests when auth is not configured (no keys)."""

    def test_07_no_config_allows_mutations(self):
        """When auth disabled, mutations work without headers."""
        # Temporarily disable auth
        keys_mod._keys = {}
        keys_mod._loaded = True

        r = client.post(
            "/api/v1/missions",
            json={"goal": "no auth config test"},
            headers={"Origin": "http://localhost:3000"},
        )
        self.assertIn(r.status_code, (201, 200))

    @classmethod
    def tearDownClass(cls):
        """Restore auth to disabled state for other test modules."""
        keys_mod._keys = {}
        keys_mod._loaded = True


# Ensure auth is disabled after this module runs
# (other tests expect no auth enforcement)
def teardown_module():
    keys_mod._keys = {}
    keys_mod._loaded = True


if __name__ == "__main__":
    unittest.main()
