"""Sprint 51 Task 51.1 — B-110 Contract Test Pack.

OpenAPI schema contract tests validating response shapes against frozen spec.
Ensures API endpoints return expected response structures (D-067 compliance).
"""
import json
import os
import sys
import unittest
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from fastapi.testclient import TestClient

# Auth headers from conftest
AUTH_HEADERS = {"Authorization": "Bearer vz_test_operator_key_001"}
VIEWER_HEADERS = {"Authorization": "Bearer vz_test_viewer_key_001"}

# Load OpenAPI spec for schema reference
OC_ROOT = Path(__file__).resolve().parent.parent.parent
SPEC_PATH = OC_ROOT / "docs" / "api" / "openapi.json"


class ContractTestBase(unittest.TestCase):
    """Base class for contract tests with shared client and spec."""

    _tmpdir = None

    @classmethod
    def setUpClass(cls):
        import tempfile
        cls._tmpdir = tempfile.mkdtemp()
        tmpdir = Path(cls._tmpdir)

        # Set up minimal server state for integration tests
        missions_dir = tmpdir / "missions"
        missions_dir.mkdir()
        approvals_dir = tmpdir / "approvals"
        approvals_dir.mkdir()

        # Create a test mission file
        (missions_dir / "mission-contract-test.json").write_text(json.dumps({
            "missionId": "contract-test-001",
            "status": "completed",
            "goal": "contract test mission",
            "stages": [{"id": "s1", "specialist": "analyst", "status": "completed"}],
        }), encoding="utf-8")

        caps_path = tmpdir / "capabilities.json"
        caps_path.write_text(json.dumps({
            "autoGenerated": True,
            "capabilities": {"deny_forensics": {"available": True}},
        }), encoding="utf-8")

        import api.server as srv
        srv.MISSIONS_DIR = missions_dir
        srv.APPROVALS_DIR = approvals_dir
        srv.TELEMETRY_PATH = tmpdir / "telemetry.jsonl"
        srv.CAPABILITIES_PATH = caps_path
        srv.SERVICES_PATH = tmpdir / "services.json"

        from api.capabilities import CapabilityChecker
        from api.normalizer import MissionNormalizer
        srv.normalizer = MissionNormalizer(
            missions_dir, srv.TELEMETRY_PATH, caps_path, approvals_dir)
        srv.capability_checker = CapabilityChecker(caps_path)

        cls.client = TestClient(srv.app)
        if SPEC_PATH.exists():
            cls.spec = json.loads(SPEC_PATH.read_text(encoding="utf-8"))
        else:
            cls.spec = {}

    @classmethod
    def tearDownClass(cls):
        import shutil
        if cls._tmpdir:
            shutil.rmtree(cls._tmpdir, ignore_errors=True)

    def assert_meta_present(self, data: dict, endpoint: str):
        """Assert response contains meta field (D-067 wrapper)."""
        self.assertIn("meta", data,
                       f"{endpoint}: Missing 'meta' in response wrapper")
        meta = data["meta"]
        self.assertIn("dataQuality", meta,
                       f"{endpoint}: Missing 'dataQuality' in meta")
        self.assertIn("generatedAt", meta,
                       f"{endpoint}: Missing 'generatedAt' in meta")

    def assert_endpoint_exists_in_spec(self, method: str, path: str):
        """Assert endpoint is documented in OpenAPI spec."""
        if not self.spec:
            self.skipTest("OpenAPI spec not available")
        paths = self.spec.get("paths", {})
        self.assertIn(path, paths,
                       f"Endpoint {path} not found in OpenAPI spec")
        self.assertIn(method, paths[path],
                       f"Method {method} not found for {path} in spec")


class TestMissionsContract(ContractTestBase):
    """Contract tests for /api/v1/missions endpoints."""

    def test_01_list_missions_shape(self):
        """GET /missions returns expected response shape."""
        resp = self.client.get("/api/v1/missions")
        self.assertEqual(resp.status_code, 200)
        data = resp.json()
        self.assert_meta_present(data, "GET /missions")
        self.assertIn("missions", data)
        self.assertIsInstance(data["missions"], list)

    def test_02_list_missions_in_spec(self):
        """GET /missions is documented in OpenAPI spec."""
        self.assert_endpoint_exists_in_spec("get", "/api/v1/missions")

    def test_03_mission_not_found_shape(self):
        """GET /missions/{id} 404 returns RFC 9457 error envelope."""
        resp = self.client.get("/api/v1/missions/nonexistent-id-12345")
        self.assertEqual(resp.status_code, 404)
        data = resp.json()
        self.assertIn("type", data)
        self.assertIn("status", data)
        self.assertIn("detail", data)
        self.assertEqual(data["status"], 404)


class TestHealthContract(ContractTestBase):
    """Contract tests for /api/v1/health endpoint."""

    def test_04_health_shape(self):
        """GET /health returns expected fields."""
        resp = self.client.get("/api/v1/health")
        self.assertEqual(resp.status_code, 200)
        data = resp.json()
        self.assertIn("status", data)
        self.assertIn("components", data)

    def test_05_health_in_spec(self):
        """GET /health is documented in OpenAPI spec."""
        self.assert_endpoint_exists_in_spec("get", "/api/v1/health")


class TestRolesContract(ContractTestBase):
    """Contract tests for /api/v1/roles endpoint."""

    def test_06_roles_shape(self):
        """GET /roles returns role objects."""
        resp = self.client.get("/api/v1/roles")
        self.assertEqual(resp.status_code, 200)
        data = resp.json()
        self.assert_meta_present(data, "GET /roles")
        self.assertIn("roles", data)
        # Roles can be dict (role_name -> details) or list
        self.assertIsInstance(data["roles"], (dict, list))

    def test_07_roles_in_spec(self):
        """GET /roles is documented in OpenAPI spec."""
        self.assert_endpoint_exists_in_spec("get", "/api/v1/roles")


class TestPoliciesContract(ContractTestBase):
    """Contract tests for /api/v1/policies endpoint."""

    def test_08_policies_list_shape(self):
        """GET /policies returns rules array and count."""
        resp = self.client.get("/api/v1/policies")
        self.assertEqual(resp.status_code, 200)
        data = resp.json()
        self.assertIn("rules", data)
        self.assertIn("count", data)
        self.assertIsInstance(data["rules"], list)
        self.assertIsInstance(data["count"], int)

    def test_09_policies_in_spec(self):
        """GET /policies is documented in OpenAPI spec."""
        self.assert_endpoint_exists_in_spec("get", "/api/v1/policies")


class TestCostContract(ContractTestBase):
    """Contract tests for /api/v1/cost endpoints."""

    def test_10_cost_summary_shape(self):
        """GET /cost/summary returns expected KPI fields."""
        resp = self.client.get("/api/v1/cost/summary")
        self.assertEqual(resp.status_code, 200)
        data = resp.json()
        self.assert_meta_present(data, "GET /cost/summary")
        self.assertIn("total_missions", data)
        self.assertIn("total_tokens", data)
        self.assertIn("total_estimated_cost", data)

    def test_11_cost_missions_shape(self):
        """GET /cost/missions returns paginated mission cost data."""
        resp = self.client.get("/api/v1/cost/missions")
        self.assertEqual(resp.status_code, 200)
        data = resp.json()
        self.assert_meta_present(data, "GET /cost/missions")
        self.assertIn("total", data)
        self.assertIn("missions", data)

    def test_12_cost_trends_shape(self):
        """GET /cost/trends returns trend buckets."""
        resp = self.client.get("/api/v1/cost/trends")
        self.assertEqual(resp.status_code, 200)
        data = resp.json()
        self.assert_meta_present(data, "GET /cost/trends")
        self.assertIn("bucket", data)
        self.assertIn("trends", data)


class TestAgentsContract(ContractTestBase):
    """Contract tests for /api/v1/agents endpoints."""

    def test_13_agents_providers_shape(self):
        """GET /agents/providers returns provider list."""
        resp = self.client.get("/api/v1/agents/providers")
        self.assertEqual(resp.status_code, 200)
        data = resp.json()
        self.assert_meta_present(data, "GET /agents/providers")
        self.assertIn("providers", data)

    def test_14_agents_roles_shape(self):
        """GET /agents/roles returns role capabilities."""
        resp = self.client.get("/api/v1/agents/roles")
        self.assertEqual(resp.status_code, 200)
        data = resp.json()
        self.assert_meta_present(data, "GET /agents/roles")
        self.assertIn("roles", data)


class TestDLQContract(ContractTestBase):
    """Contract tests for /api/v1/dlq endpoint."""

    def test_15_dlq_list_shape(self):
        """GET /dlq returns entries list."""
        resp = self.client.get("/api/v1/dlq")
        self.assertEqual(resp.status_code, 200)
        data = resp.json()
        self.assertIn("entries", data)
        self.assertIsInstance(data["entries"], list)


class TestAlertsContract(ContractTestBase):
    """Contract tests for /api/v1/alerts endpoint."""

    def test_16_alerts_shape(self):
        """GET /alerts/rules returns alerts rules list with meta."""
        resp = self.client.get("/api/v1/alerts/rules")
        self.assertEqual(resp.status_code, 200)
        data = resp.json()
        self.assert_meta_present(data, "GET /alerts/rules")
        self.assertIn("rules", data)
        self.assertIsInstance(data["rules"], list)


class TestDashboardContract(ContractTestBase):
    """Contract tests for /api/v1/dashboard endpoint."""

    def test_17_dashboard_shape(self):
        """GET /dashboard/summary returns system overview."""
        resp = self.client.get("/api/v1/dashboard/summary")
        self.assertEqual(resp.status_code, 200)
        data = resp.json()
        self.assert_meta_present(data, "GET /dashboard/summary")


class TestErrorEnvelopeContract(ContractTestBase):
    """Contract tests for RFC 9457 error envelope."""

    def test_18_404_error_envelope(self):
        """404 errors use RFC 9457 format."""
        resp = self.client.get("/api/v1/nonexistent-endpoint-xyz")
        self.assertEqual(resp.status_code, 404)
        data = resp.json()
        self.assertIn("detail", data)

    def test_19_error_has_type_field(self):
        """Error responses include type field."""
        resp = self.client.get("/api/v1/missions/fake-id-999")
        self.assertEqual(resp.status_code, 404)
        data = resp.json()
        self.assertIn("type", data)
        self.assertIn("status", data)


class TestBreakingChangeDetection(unittest.TestCase):
    """Tests for the contract_check.py tool itself."""

    def test_20_extract_endpoints(self):
        """contract_check extracts endpoints from spec."""
        sys.path.insert(0, str(OC_ROOT / "tools"))
        from contract_check import extract_endpoints

        spec = {
            "paths": {
                "/api/v1/test": {
                    "get": {
                        "parameters": [
                            {"name": "q", "in": "query", "required": True}
                        ],
                        "responses": {
                            "200": {
                                "content": {
                                    "application/json": {
                                        "schema": {"$ref": "#/components/schemas/TestResp"}
                                    }
                                }
                            }
                        },
                        "tags": ["test"],
                    }
                }
            }
        }
        eps = extract_endpoints(spec)
        self.assertEqual(len(eps), 1)
        self.assertIn("GET /api/v1/test", eps)
        self.assertEqual(eps["GET /api/v1/test"]["params"][0]["name"], "q")

    def test_21_detect_removed_endpoint(self):
        """contract_check detects removed endpoints."""
        sys.path.insert(0, str(OC_ROOT / "tools"))
        from contract_check import check_breaking_changes

        baseline = {"paths": {"/api/v1/foo": {"get": {"responses": {}}}}}
        current = {"paths": {}}
        issues = check_breaking_changes(baseline, current)
        self.assertTrue(any("removed" in i.lower() for i in issues))

    def test_22_no_breaking_when_identical(self):
        """contract_check reports no issues for identical specs."""
        sys.path.insert(0, str(OC_ROOT / "tools"))
        from contract_check import check_breaking_changes

        spec = {"paths": {"/api/v1/test": {"get": {"responses": {}}}}}
        issues = check_breaking_changes(spec, spec)
        self.assertEqual(len(issues), 0)


if __name__ == "__main__":
    unittest.main()
