"""Sprint 12 E2E Test Suite — D-098: API-level E2E with httpx + pytest.

12+ scenarios covering the full Vezir API flow:
  1. Health check → system operational
  2. Capabilities listing
  3. Mission list → empty state
  4. Mission creation + detail + stages flow
  5. Multi-mission list with ordering
  6. Approval list → empty and populated
  7. Approval approve mutation (D-096 lifecycle)
  8. Approval reject mutation (D-090 destructive)
  9. Approval mutation FSM guard (409 conflict)
  10. Mission cancel mutation
  11. Mission retry mutation
  12. Mission mutation FSM guard (409 conflict)
  13. Telemetry query with mission_id filter
  14. Host header security (D-070)
  15. CSRF validation for POST (D-089)
  16. OpenAPI spec availability
"""
import json
import os
import shutil
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def _make_e2e_client():
    """Create isolated TestClient with fresh temp data directories."""
    tmpdir = tempfile.mkdtemp(prefix="e2e_")
    missions_dir = Path(tmpdir) / "missions"
    missions_dir.mkdir()
    approvals_dir = Path(tmpdir) / "approvals"
    approvals_dir.mkdir()
    telemetry_path = Path(tmpdir) / "telemetry.jsonl"
    caps_path = Path(tmpdir) / "capabilities.json"
    services_path = Path(tmpdir) / "services.json"
    log_path = Path(tmpdir) / "api.log"

    caps_path.write_text(json.dumps({
        "autoGenerated": True,
        "capabilities": {
            "deny_forensics": {"available": True},
            "quality_gates": {"available": True},
            "artifact_extraction": {"available": True},
        },
    }), encoding="utf-8")

    import api.server as srv
    srv.MISSIONS_DIR = missions_dir
    srv.APPROVALS_DIR = approvals_dir
    srv.TELEMETRY_PATH = telemetry_path
    srv.CAPABILITIES_PATH = caps_path
    srv.SERVICES_PATH = services_path
    srv.API_LOG_PATH = log_path

    from api.normalizer import MissionNormalizer
    from api.capabilities import CapabilityChecker
    srv.normalizer = MissionNormalizer(
        missions_dir, telemetry_path, caps_path, approvals_dir)
    srv.capability_checker = CapabilityChecker(str(caps_path))

    from fastapi.testclient import TestClient
    client = TestClient(srv.app)
    return client, tmpdir, missions_dir, approvals_dir, telemetry_path


def _seed_mission(missions_dir, mission_id, state="completed", goal="E2E test",
                  stages=None):
    """Seed a mission JSON file."""
    data = {
        "missionId": mission_id,
        "status": state,
        "goal": goal,
        "stages": stages or [
            {"id": "s0", "specialist": "analyst", "status": "completed"},
            {"id": "s1", "specialist": "developer", "status": "completed"},
        ],
    }
    fpath = missions_dir / f"{mission_id}.json"
    fpath.write_text(json.dumps(data), encoding="utf-8")
    return data


def _seed_mission_state(missions_dir, mission_id, state):
    """Seed a mission state.json (FSM state source)."""
    state_dir = missions_dir / mission_id
    state_dir.mkdir(parents=True, exist_ok=True)
    state_path = state_dir / "state.json"
    state_path.write_text(json.dumps({"state": state}), encoding="utf-8")


def _seed_approval(approvals_dir, apv_id, status="pending",
                   mission_id="mission-e2e-1", tool_name="shell", risk="high"):
    """Seed an approval JSON file."""
    data = {
        "approvalId": apv_id,
        "missionId": mission_id,
        "status": status,
        "toolName": tool_name,
        "risk": risk,
        "requestedAt": "2026-03-26T12:00:00+00:00",
    }
    fpath = approvals_dir / f"{apv_id}.json"
    fpath.write_text(json.dumps(data), encoding="utf-8")
    return data


def _seed_telemetry(telemetry_path, events):
    """Seed telemetry JSONL file."""
    lines = [json.dumps(e) for e in events]
    telemetry_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# ── E2E Test Scenarios ───────────────────────────────────────────

class TestE2E_01_HealthCheck(unittest.TestCase):
    """Scenario 1: Health endpoint returns system status."""

    @classmethod
    def setUpClass(cls):
        cls.client, cls.tmpdir, *_ = _make_e2e_client()

    @classmethod
    def tearDownClass(cls):
        shutil.rmtree(cls.tmpdir, ignore_errors=True)

    def test_health_returns_ok(self):
        r = self.client.get("/api/v1/health")
        self.assertEqual(r.status_code, 200)
        data = r.json()
        self.assertIn(data["status"], ("ok", "degraded"))
        self.assertIn("api", data["components"])
        self.assertEqual(data["components"]["api"]["status"], "ok")

    def test_health_meta_envelope(self):
        r = self.client.get("/api/v1/health")
        meta = r.json()["meta"]
        self.assertIn("dataQuality", meta)
        self.assertIn("generatedAt", meta)
        self.assertIn("sourcesUsed", meta)


class TestE2E_02_Capabilities(unittest.TestCase):
    """Scenario 2: Capabilities listing with tri-state."""

    @classmethod
    def setUpClass(cls):
        cls.client, cls.tmpdir, *_ = _make_e2e_client()

    @classmethod
    def tearDownClass(cls):
        shutil.rmtree(cls.tmpdir, ignore_errors=True)

    def test_capabilities_lists_seeded(self):
        r = self.client.get("/api/v1/capabilities")
        self.assertEqual(r.status_code, 200)
        caps = r.json()["capabilities"]
        self.assertIn("deny_forensics", caps)
        self.assertEqual(caps["deny_forensics"]["status"], "available")

    def test_capabilities_meta(self):
        r = self.client.get("/api/v1/capabilities")
        self.assertEqual(r.json()["meta"]["dataQuality"], "fresh")


class TestE2E_03_MissionEmpty(unittest.TestCase):
    """Scenario 3: Mission list returns empty when no missions exist."""

    @classmethod
    def setUpClass(cls):
        cls.client, cls.tmpdir, *_ = _make_e2e_client()

    @classmethod
    def tearDownClass(cls):
        shutil.rmtree(cls.tmpdir, ignore_errors=True)

    def test_empty_mission_list(self):
        r = self.client.get("/api/v1/missions")
        self.assertEqual(r.status_code, 200)
        self.assertEqual(r.json()["missions"], [])

    def test_nonexistent_mission_404(self):
        r = self.client.get("/api/v1/missions/does-not-exist")
        self.assertEqual(r.status_code, 404)


class TestE2E_04_MissionFlow(unittest.TestCase):
    """Scenario 4: Mission creation → detail → stages flow."""

    @classmethod
    def setUpClass(cls):
        cls.client, cls.tmpdir, cls.missions_dir, *_ = _make_e2e_client()
        _seed_mission(cls.missions_dir, "mission-e2e-flow", "completed",
                      "Full E2E flow test", stages=[
                          {"id": "s0", "specialist": "analyst", "status": "completed"},
                          {"id": "s1", "specialist": "developer", "status": "completed"},
                          {"id": "s2", "specialist": "tester", "status": "completed"},
                      ])

    @classmethod
    def tearDownClass(cls):
        shutil.rmtree(cls.tmpdir, ignore_errors=True)

    def test_mission_appears_in_list(self):
        r = self.client.get("/api/v1/missions")
        missions = r.json()["missions"]
        ids = [m["missionId"] for m in missions]
        self.assertIn("mission-e2e-flow", ids)

    def test_mission_detail(self):
        r = self.client.get("/api/v1/missions/mission-e2e-flow")
        self.assertEqual(r.status_code, 200)
        mission = r.json()["mission"]
        self.assertEqual(mission["missionId"], "mission-e2e-flow")
        self.assertEqual(mission["goal"], "Full E2E flow test")

    def test_mission_stages(self):
        r = self.client.get("/api/v1/missions/mission-e2e-flow/stages")
        self.assertEqual(r.status_code, 200)
        stages = r.json()["stages"]
        self.assertEqual(len(stages), 3)

    def test_single_stage(self):
        r = self.client.get("/api/v1/missions/mission-e2e-flow/stages/0")
        self.assertEqual(r.status_code, 200)

    def test_stage_out_of_range_404(self):
        r = self.client.get("/api/v1/missions/mission-e2e-flow/stages/99")
        self.assertEqual(r.status_code, 404)


class TestE2E_05_MultiMission(unittest.TestCase):
    """Scenario 5: Multiple missions coexist in listing."""

    @classmethod
    def setUpClass(cls):
        cls.client, cls.tmpdir, cls.missions_dir, *_ = _make_e2e_client()
        _seed_mission(cls.missions_dir, "mission-alpha", "completed", "Alpha")
        _seed_mission(cls.missions_dir, "mission-beta", "failed", "Beta")
        _seed_mission(cls.missions_dir, "mission-gamma", "executing", "Gamma")

    @classmethod
    def tearDownClass(cls):
        shutil.rmtree(cls.tmpdir, ignore_errors=True)

    def test_all_missions_listed(self):
        r = self.client.get("/api/v1/missions")
        missions = r.json()["missions"]
        ids = {m["missionId"] for m in missions}
        self.assertEqual(ids, {"mission-alpha", "mission-beta", "mission-gamma"})

    def test_each_mission_accessible(self):
        for mid in ["mission-alpha", "mission-beta", "mission-gamma"]:
            r = self.client.get(f"/api/v1/missions/{mid}")
            self.assertEqual(r.status_code, 200, f"Failed for {mid}")


class TestE2E_06_ApprovalFlow(unittest.TestCase):
    """Scenario 6: Approval list — empty and populated."""

    @classmethod
    def setUpClass(cls):
        cls.client, cls.tmpdir, cls.missions_dir, cls.approvals_dir, _ = _make_e2e_client()
        _seed_approval(cls.approvals_dir, "apv-e2e-1", "pending")
        _seed_approval(cls.approvals_dir, "apv-e2e-2", "approved")

    @classmethod
    def tearDownClass(cls):
        shutil.rmtree(cls.tmpdir, ignore_errors=True)

    def test_approvals_list(self):
        r = self.client.get("/api/v1/approvals")
        self.assertEqual(r.status_code, 200)
        approvals = r.json()["approvals"]
        self.assertEqual(len(approvals), 2)

    def test_approval_detail(self):
        r = self.client.get("/api/v1/approvals/apv-e2e-1")
        self.assertEqual(r.status_code, 200)

    def test_approval_not_found(self):
        r = self.client.get("/api/v1/approvals/nonexistent")
        self.assertEqual(r.status_code, 404)


class TestE2E_07_ApproveFlow(unittest.TestCase):
    """Scenario 7: Approve mutation — full D-096 lifecycle."""

    @classmethod
    def setUpClass(cls):
        cls.client, cls.tmpdir, cls.missions_dir, cls.approvals_dir, _ = _make_e2e_client()
        _seed_approval(cls.approvals_dir, "apv-approve-1", "pending",
                       mission_id="mission-apv-1")

    @classmethod
    def tearDownClass(cls):
        shutil.rmtree(cls.tmpdir, ignore_errors=True)

    def test_approve_returns_requested(self):
        r = self.client.post(
            "/api/v1/approvals/apv-approve-1/approve",
            headers={
                "Origin": "http://localhost:3000",
                "X-Tab-Id": "tab-1",
                "X-Session-Id": "sess-1",
            },
        )
        self.assertEqual(r.status_code, 200)
        data = r.json()
        self.assertEqual(data["lifecycleState"], "requested")
        self.assertIn("requestId", data)
        self.assertEqual(data["targetId"], "apv-approve-1")
        self.assertIn("timeoutAt", data)

    def test_approve_creates_signal_artifact(self):
        # Artifact should exist after approve
        mission_dir = self.missions_dir / "mission-apv-1"
        if mission_dir.exists():
            artifacts = list(mission_dir.glob("approve-request-req-*.json"))
            self.assertGreaterEqual(len(artifacts), 1)


class TestE2E_08_RejectFlow(unittest.TestCase):
    """Scenario 8: Reject mutation — D-090 destructive action."""

    @classmethod
    def setUpClass(cls):
        cls.client, cls.tmpdir, cls.missions_dir, cls.approvals_dir, _ = _make_e2e_client()
        _seed_approval(cls.approvals_dir, "apv-reject-1", "pending",
                       mission_id="mission-rej-1")

    @classmethod
    def tearDownClass(cls):
        shutil.rmtree(cls.tmpdir, ignore_errors=True)

    def test_reject_returns_requested(self):
        r = self.client.post(
            "/api/v1/approvals/apv-reject-1/reject",
            headers={"Origin": "http://localhost:3000"},
        )
        self.assertEqual(r.status_code, 200)
        data = r.json()
        self.assertEqual(data["lifecycleState"], "requested")
        self.assertEqual(data["targetId"], "apv-reject-1")


class TestE2E_09_ApprovalFSMGuard(unittest.TestCase):
    """Scenario 9: Mutation FSM guard — 409 on non-pending approval."""

    @classmethod
    def setUpClass(cls):
        cls.client, cls.tmpdir, cls.missions_dir, cls.approvals_dir, _ = _make_e2e_client()
        _seed_approval(cls.approvals_dir, "apv-done-1", "approved")

    @classmethod
    def tearDownClass(cls):
        shutil.rmtree(cls.tmpdir, ignore_errors=True)

    def test_approve_non_pending_409(self):
        r = self.client.post(
            "/api/v1/approvals/apv-done-1/approve",
            headers={"Origin": "http://localhost:3000"},
        )
        self.assertEqual(r.status_code, 409)

    def test_reject_non_pending_409(self):
        r = self.client.post(
            "/api/v1/approvals/apv-done-1/reject",
            headers={"Origin": "http://localhost:3000"},
        )
        self.assertEqual(r.status_code, 409)

    def test_approve_not_found_404(self):
        r = self.client.post(
            "/api/v1/approvals/nonexistent/approve",
            headers={"Origin": "http://localhost:3000"},
        )
        self.assertEqual(r.status_code, 404)


class TestE2E_10_MissionCancel(unittest.TestCase):
    """Scenario 10: Mission cancel mutation."""

    @classmethod
    def setUpClass(cls):
        cls.client, cls.tmpdir, cls.missions_dir, *_ = _make_e2e_client()
        _seed_mission(cls.missions_dir, "mission-cancel-1", "executing")
        _seed_mission_state(cls.missions_dir, "mission-cancel-1", "executing")

    @classmethod
    def tearDownClass(cls):
        shutil.rmtree(cls.tmpdir, ignore_errors=True)

    def test_a_cancel_executing_mission(self):
        r = self.client.post(
            "/api/v1/missions/mission-cancel-1/cancel",
            headers={
                "Origin": "http://localhost:3000",
                "X-Tab-Id": "tab-c",
                "X-Session-Id": "sess-c",
            },
        )
        self.assertEqual(r.status_code, 200)
        data = r.json()
        self.assertEqual(data["lifecycleState"], "requested")
        self.assertEqual(data["targetId"], "mission-cancel-1")

    def test_b_cancel_creates_signal_artifact(self):
        mission_dir = self.missions_dir / "mission-cancel-1"
        artifacts = list(mission_dir.glob("cancel-request-req-*.json"))
        self.assertGreaterEqual(len(artifacts), 1)


class TestE2E_11_MissionRetry(unittest.TestCase):
    """Scenario 11: Mission retry mutation — failed → retry."""

    @classmethod
    def setUpClass(cls):
        cls.client, cls.tmpdir, cls.missions_dir, *_ = _make_e2e_client()
        _seed_mission(cls.missions_dir, "mission-retry-1", "failed")
        _seed_mission_state(cls.missions_dir, "mission-retry-1", "failed")

    @classmethod
    def tearDownClass(cls):
        shutil.rmtree(cls.tmpdir, ignore_errors=True)

    def test_retry_failed_mission(self):
        r = self.client.post(
            "/api/v1/missions/mission-retry-1/retry",
            headers={"Origin": "http://localhost:3000"},
        )
        self.assertEqual(r.status_code, 200)
        data = r.json()
        self.assertEqual(data["lifecycleState"], "requested")


class TestE2E_12_MissionFSMGuard(unittest.TestCase):
    """Scenario 12: Mission mutation FSM guard — 409 on invalid state."""

    @classmethod
    def setUpClass(cls):
        cls.client, cls.tmpdir, cls.missions_dir, *_ = _make_e2e_client()
        _seed_mission(cls.missions_dir, "mission-done-1", "completed")
        _seed_mission_state(cls.missions_dir, "mission-done-1", "completed")
        _seed_mission(cls.missions_dir, "mission-active-1", "executing")
        _seed_mission_state(cls.missions_dir, "mission-active-1", "executing")

    @classmethod
    def tearDownClass(cls):
        shutil.rmtree(cls.tmpdir, ignore_errors=True)

    def test_cancel_completed_409(self):
        r = self.client.post(
            "/api/v1/missions/mission-done-1/cancel",
            headers={"Origin": "http://localhost:3000"},
        )
        self.assertEqual(r.status_code, 409)

    def test_retry_executing_409(self):
        r = self.client.post(
            "/api/v1/missions/mission-active-1/retry",
            headers={"Origin": "http://localhost:3000"},
        )
        self.assertEqual(r.status_code, 409)

    def test_cancel_not_found_404(self):
        r = self.client.post(
            "/api/v1/missions/nonexistent/cancel",
            headers={"Origin": "http://localhost:3000"},
        )
        self.assertEqual(r.status_code, 404)


class TestE2E_13_Telemetry(unittest.TestCase):
    """Scenario 13: Telemetry query with mission_id filter."""

    @classmethod
    def setUpClass(cls):
        cls.client, cls.tmpdir, cls.missions_dir, _, cls.telemetry_path = _make_e2e_client()
        _seed_telemetry(cls.telemetry_path, [
            {"type": "policy_deny", "missionId": "m-1", "timestamp": "2026-03-26T10:00:00Z",
             "data": {"tool": "shell", "reason": "blocked"}},
            {"type": "policy_deny", "missionId": "m-2", "timestamp": "2026-03-26T10:01:00Z",
             "data": {"tool": "file_write", "reason": "path_violation"}},
            {"type": "tool_call", "missionId": "m-1", "timestamp": "2026-03-26T10:02:00Z",
             "data": {"tool": "read_file"}},
        ])

    @classmethod
    def tearDownClass(cls):
        shutil.rmtree(cls.tmpdir, ignore_errors=True)

    def test_telemetry_all(self):
        r = self.client.get("/api/v1/telemetry")
        self.assertEqual(r.status_code, 200)
        events = r.json()["events"]
        self.assertGreaterEqual(len(events), 1)

    def test_telemetry_filter_by_mission(self):
        r = self.client.get("/api/v1/telemetry?mission_id=m-1")
        self.assertEqual(r.status_code, 200)
        events = r.json()["events"]
        for e in events:
            if e.get("missionId"):
                self.assertEqual(e["missionId"], "m-1")

    def test_telemetry_limit(self):
        r = self.client.get("/api/v1/telemetry?limit=1")
        self.assertEqual(r.status_code, 200)
        events = r.json()["events"]
        self.assertLessEqual(len(events), 1)


class TestE2E_14_HostSecurity(unittest.TestCase):
    """Scenario 14: D-070 host header validation."""

    @classmethod
    def setUpClass(cls):
        cls.client, cls.tmpdir, *_ = _make_e2e_client()

    @classmethod
    def tearDownClass(cls):
        shutil.rmtree(cls.tmpdir, ignore_errors=True)

    def test_valid_host_ok(self):
        r = self.client.get("/api/v1/health")
        self.assertEqual(r.status_code, 200)

    def test_invalid_host_403(self):
        r = self.client.get("/api/v1/health",
                            headers={"Host": "attacker.com"})
        self.assertEqual(r.status_code, 403)

    def test_localhost_with_port_ok(self):
        r = self.client.get("/api/v1/health",
                            headers={"Host": "localhost:8003"})
        self.assertEqual(r.status_code, 200)


class TestE2E_15_CSRFValidation(unittest.TestCase):
    """Scenario 15: D-089 CSRF — Origin header required for POST."""

    @classmethod
    def setUpClass(cls):
        cls.client, cls.tmpdir, cls.missions_dir, cls.approvals_dir, _ = _make_e2e_client()
        _seed_approval(cls.approvals_dir, "apv-csrf-1", "pending",
                       mission_id="mission-csrf-1")

    @classmethod
    def tearDownClass(cls):
        shutil.rmtree(cls.tmpdir, ignore_errors=True)

    def test_post_without_origin_403(self):
        r = self.client.post("/api/v1/approvals/apv-csrf-1/approve")
        self.assertEqual(r.status_code, 403)

    def test_post_with_wrong_origin_403(self):
        r = self.client.post(
            "/api/v1/approvals/apv-csrf-1/approve",
            headers={"Origin": "http://evil.com"},
        )
        self.assertEqual(r.status_code, 403)

    def test_post_with_valid_origin_ok(self):
        r = self.client.post(
            "/api/v1/approvals/apv-csrf-1/approve",
            headers={"Origin": "http://localhost:3000"},
        )
        # Should pass CSRF (may be 200 or 409 depending on state, but not 403)
        self.assertNotEqual(r.status_code, 403)


class TestE2E_16_OpenAPISpec(unittest.TestCase):
    """Scenario 16: OpenAPI spec is available and valid."""

    @classmethod
    def setUpClass(cls):
        cls.client, cls.tmpdir, *_ = _make_e2e_client()

    @classmethod
    def tearDownClass(cls):
        shutil.rmtree(cls.tmpdir, ignore_errors=True)

    def test_openapi_json(self):
        r = self.client.get("/openapi.json")
        self.assertEqual(r.status_code, 200)
        spec = r.json()
        self.assertIn("openapi", spec)
        self.assertIn("paths", spec)
        self.assertGreaterEqual(len(spec["paths"]), 10)

    def test_openapi_has_all_tags(self):
        r = self.client.get("/openapi.json")
        spec = r.json()
        tags_in_paths = set()
        for path_data in spec["paths"].values():
            for method_data in path_data.values():
                for tag in method_data.get("tags", []):
                    tags_in_paths.add(tag)
        expected = {"missions", "approvals", "health", "telemetry", "events",
                    "approval-mutations", "mission-mutations"}
        self.assertTrue(expected.issubset(tags_in_paths))


if __name__ == "__main__":
    unittest.main(verbosity=2)
